[package]
name = "arborio-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arborio-utils = { path = "../utils", default-features = false }
arborio-modloader = { path = "../modloader", default-features = false }
arborio-maploader = { path = "../maploader", default-features = false }
arborio-gfxloader = { path = "../gfxloader", default-features = false }
arborio-walker = { path = "../walker", default-features = false }

serde = { version = "^1.0", features = ["derive"] }  # TODO: how can we not duplicate this dep and instead re-export it from utils?
confy = "^0.5"
log = "0.4.16"
parking_lot = "^0.12"
serde_yaml = "^0.9"
enum-iterator = "^1.2"
lazy_static = "^1.4"
regex = { version = "^1.5", default-features = false, features = ["std"] }
itertools = "^0.10"
rand = "0.8.5"
once_cell = "^1.17"